# Generated by Django 2.2.9 on 2019-12-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mypost_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='pic',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='video',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
